# rest.http
### ============================================================================
### ПЕРЕМЕННЫЕ
### ============================================================================
@baseUrl = http://localhost:8080
@contentType = application/json

# @ivan_token = ВСТАВЬТЕ_СЮДА_ТОКЕН_IVAN
# @hacker_token = ВСТАВЬТЕ_СЮДА_ТОКЕН_HACKER
# @admin_token = ВСТАВЬТЕ_СЮДА_ТОКЕН_ADMIN

@ivan_token = 442f8412-202c-453f-b906-e786241026e0
@hacker_token = bdd87a9d-ec72-439d-9a70-5fe66c625c9a
@admin_token = b485f3ea-9b2a-4520-8a9b-4ecd5510910b

@ivan_advert_id = 1
@hacker_advert_id = 2

### ============================================================================
### 1. СОЗДАНИЕ ПОЛЬЗОВАТЕЛЕЙ
### ============================================================================

### Создать обычного пользователя ivan
POST {{baseUrl}}/user
Content-Type: {{contentType}}

{
  "username": "ivan",
  "password": "123",
  "role": "user"
}

### Создать пользователя hacker
POST {{baseUrl}}/user
Content-Type: {{contentType}}

{
  "username": "hacker",
  "password": "321"
}

#### ИСПРАВЛЕНИЕ: Пример создания пользователя с ролью admin ####
### Создать пользователя admin
POST {{baseUrl}}/user
Content-Type: {{contentType}}

{
  "username": "admin_user",
  "password": "admin123",
  "role": "admin"
}

### ============================================================================
### 2. АУТЕНТИФИКАЦИЯ
### ============================================================================

### Логин ivan (скопируйте токен из ответа и вставьте выше)
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "username": "ivan",
  "password": "123"
}

### Логин hacker (скопируйте токен из ответа и вставьте выше)
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "username": "hacker",
  "password": "321"
}

### Логин admin_user (скопируйте токен из ответа и вставьте выше)
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "username": "admin_user",
  "password": "admin123"
}

### ============================================================================
### 3. РАБОТА С ПОЛЬЗОВАТЕЛЯМИ (GET /user и GET /user/{user_id?})
### ============================================================================

#### ИСПРАВЛЕНИЕ: Получение списка всех пользователей (работает только с токеном админа) ####
### Получить список пользователей (Admin only)
GET {{baseUrl}}/user
x-token: {{admin_token}}


### Получить конкретного пользователя (Доступно всем)
GET {{baseUrl}}/user/1

### ============================================================================
### 4. РАБОТА С ОБЪЯВЛЕНИЯМИ (с пагинацией)
### ============================================================================

### Иван создает объявление (Требуется токен!)
POST {{baseUrl}}/advertisement
Content-Type: {{contentType}}
x-token: {{ivan_token}}

{
  "title": "Продам гараж",
  "description": "Теплый и сухой",
  "price": 100000.0,
  "author": "ivan"
}

#### ИСПРАВЛЕНИЕ: Поиск объявлений с поддержкой пагинации (offset и limit) ####
### Поиск объявлений с пагинацией (взять 5)
GET {{baseUrl}}/advertisement?title=гараж&offset=0&limit=5


### ============================================================================
### 5. ПРОВЕРКА ЗАЩИТЫ И ОБНОВЛЕНИЯ
### ============================================================================

#### ИСПРАВЛЕНИЕ: Админ может изменить роль пользователя ####
### Админ изменяет роль пользователя ivan на admin

### Хакер пытается изменить объявление Ивана (ДОЛЖНО ВЕРНУТЬ 403)
PATCH {{baseUrl}}/advertisement/{{ivan_advert_id}}
Content-Type: {{contentType}}
x-token: {{hacker_token}}

{
  "price": 1.0
}

#### ИСПРАВЛЕНИЕ: Админ может изменить роль пользователя ####
### Админ изменяет роль пользователя ivan на admin
PATCH {{baseUrl}}/user/1
Content-Type: {{contentType}}
x-token: {{admin_token}}

{
  "role": "admin"
}

### Иван обновляет СВОЕ объявление (ДОЛЖНО ВЕРНУТЬ 200)
PATCH {{baseUrl}}/advertisement/{{ivan_advert_id}}
Content-Type: {{contentType}}
x-token: {{ivan_token}}

{
  "price": 150000.0
}